doesn't support non-Linux

diff --git a/yasp b/yasp
--- a/yasp
+++ b/yasp
@@ -15,12 +15,14 @@ if [ ! -z `grep Linux `uname -o`` ]; then
     echo "kernel: Linux"
 elif [ ! -z `grep BSD `uname -o`` ]; then
     echo "kernel: *BSD"
+    echo "it doesn't support aufs, aborting..."
+    exit 1
 else
     echo "kernel: unknown, aborting..."
     exit 1
 fi
 
-#FIXME: kFreeBSD support
+#FIXME: kFreeBSD support?
 if [ -z `grep CONFIG_AUFS_FS "/boot/config-`uname -a| cut -d' ' -f3`"` ]; then
      echo "Your kernel seems to not support aufs, aborting..."
      exit 1
